### ISSUE TITLE
Stereo sound with app_jack

### ISSUE THREAD

**Issue by epipenau** [pruiz/asterisk#1]
hi,

i've tried to pipe a 2-channel opus call to a stereo port or ports.  however it only creates one channel. I can't manage to get the stereo sound from both speakers...

can someone help me with this?

**Comment by epipenau** [comment]
plz

**Comment by pruiz** [comment]
Sorry, but this is not asterisk upstream repository, nor any oficial support channel. Just my own asterisk's source code fork.
